// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressType int32

const (
	AddressType_ADDR_TYPE_IPV4   AddressType = 1
	AddressType_ADDR_TYPE_DOMAIN AddressType = 3
	AddressType_ADDR_TYPE_IPV6   AddressType = 4
)

var AddressType_name = map[int32]string{
	1: "ADDR_TYPE_IPV4",
	3: "ADDR_TYPE_DOMAIN",
	4: "ADDR_TYPE_IPV6",
}
var AddressType_value = map[string]int32{
	"ADDR_TYPE_IPV4":   1,
	"ADDR_TYPE_DOMAIN": 3,
	"ADDR_TYPE_IPV6":   4,
}

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}
func (x AddressType) String() string {
	return proto.EnumName(AddressType_name, int32(x))
}
func (x *AddressType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AddressType_value, data, "AddressType")
	if err != nil {
		return err
	}
	*x = AddressType(value)
	return nil
}
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{0}
}

type OPType int32

const (
	OPType_OP_TYPE_PROXY   OPType = 1
	OPType_OP_TYPE_FORWARD OPType = 2
)

var OPType_name = map[int32]string{
	1: "OP_TYPE_PROXY",
	2: "OP_TYPE_FORWARD",
}
var OPType_value = map[string]int32{
	"OP_TYPE_PROXY":   1,
	"OP_TYPE_FORWARD": 2,
}

func (x OPType) Enum() *OPType {
	p := new(OPType)
	*p = x
	return p
}
func (x OPType) String() string {
	return proto.EnumName(OPType_name, int32(x))
}
func (x *OPType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OPType_value, data, "OPType")
	if err != nil {
		return err
	}
	*x = OPType(value)
	return nil
}
func (OPType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{1}
}

type AuthResult int32

const (
	AuthResult_AUTH_OK               AuthResult = 0
	AuthResult_AUTH_USER_PWD_INVALID AuthResult = 10000
	AuthResult_AUTH_INVALID_ADDRESS  AuthResult = 10001
)

var AuthResult_name = map[int32]string{
	0:     "AUTH_OK",
	10000: "AUTH_USER_PWD_INVALID",
	10001: "AUTH_INVALID_ADDRESS",
}
var AuthResult_value = map[string]int32{
	"AUTH_OK":               0,
	"AUTH_USER_PWD_INVALID": 10000,
	"AUTH_INVALID_ADDRESS":  10001,
}

func (x AuthResult) Enum() *AuthResult {
	p := new(AuthResult)
	*p = x
	return p
}
func (x AuthResult) String() string {
	return proto.EnumName(AuthResult_name, int32(x))
}
func (x *AuthResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthResult_value, data, "AuthResult")
	if err != nil {
		return err
	}
	*x = AuthResult(value)
	return nil
}
func (AuthResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{2}
}

type RelayAddress struct {
	AddressType          *int32   `protobuf:"varint,1,opt,name=address_type" json:"address_type,omitempty"`
	Address              *string  `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Name                 *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Port                 *uint32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayAddress) Reset()         { *m = RelayAddress{} }
func (m *RelayAddress) String() string { return proto.CompactTextString(m) }
func (*RelayAddress) ProtoMessage()    {}
func (*RelayAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{0}
}
func (m *RelayAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayAddress.Unmarshal(m, b)
}
func (m *RelayAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayAddress.Marshal(b, m, deterministic)
}
func (dst *RelayAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayAddress.Merge(dst, src)
}
func (m *RelayAddress) XXX_Size() int {
	return xxx_messageInfo_RelayAddress.Size(m)
}
func (m *RelayAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayAddress.DiscardUnknown(m)
}

var xxx_messageInfo_RelayAddress proto.InternalMessageInfo

func (m *RelayAddress) GetAddressType() int32 {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return 0
}

func (m *RelayAddress) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *RelayAddress) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RelayAddress) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type AuthMsgReq struct {
	User                 *string       `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Pwd                  *string       `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	Address              *RelayAddress `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	OpType               *int32        `protobuf:"varint,4,opt,name=op_type" json:"op_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AuthMsgReq) Reset()         { *m = AuthMsgReq{} }
func (m *AuthMsgReq) String() string { return proto.CompactTextString(m) }
func (*AuthMsgReq) ProtoMessage()    {}
func (*AuthMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{1}
}
func (m *AuthMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMsgReq.Unmarshal(m, b)
}
func (m *AuthMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMsgReq.Marshal(b, m, deterministic)
}
func (dst *AuthMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMsgReq.Merge(dst, src)
}
func (m *AuthMsgReq) XXX_Size() int {
	return xxx_messageInfo_AuthMsgReq.Size(m)
}
func (m *AuthMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMsgReq proto.InternalMessageInfo

func (m *AuthMsgReq) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *AuthMsgReq) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *AuthMsgReq) GetAddress() *RelayAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AuthMsgReq) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

type AuthMsgRsp struct {
	Result               *int32   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Token                *uint32  `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMsgRsp) Reset()         { *m = AuthMsgRsp{} }
func (m *AuthMsgRsp) String() string { return proto.CompactTextString(m) }
func (*AuthMsgRsp) ProtoMessage()    {}
func (*AuthMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_532a9a2152fb403c, []int{2}
}
func (m *AuthMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMsgRsp.Unmarshal(m, b)
}
func (m *AuthMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMsgRsp.Marshal(b, m, deterministic)
}
func (dst *AuthMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMsgRsp.Merge(dst, src)
}
func (m *AuthMsgRsp) XXX_Size() int {
	return xxx_messageInfo_AuthMsgRsp.Size(m)
}
func (m *AuthMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMsgRsp proto.InternalMessageInfo

func (m *AuthMsgRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *AuthMsgRsp) GetToken() uint32 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func init() {
	proto.RegisterType((*RelayAddress)(nil), "msg.RelayAddress")
	proto.RegisterType((*AuthMsgReq)(nil), "msg.AuthMsgReq")
	proto.RegisterType((*AuthMsgRsp)(nil), "msg.AuthMsgRsp")
	proto.RegisterEnum("msg.AddressType", AddressType_name, AddressType_value)
	proto.RegisterEnum("msg.OPType", OPType_name, OPType_value)
	proto.RegisterEnum("msg.AuthResult", AuthResult_name, AuthResult_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_msg_532a9a2152fb403c) }

var fileDescriptor_msg_532a9a2152fb403c = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xdb, 0x6a, 0xf2, 0x40,
	0x14, 0x85, 0xff, 0x18, 0x0f, 0xb8, 0x63, 0x74, 0xdc, 0xbf, 0x85, 0xb4, 0x57, 0x92, 0x2b, 0xb1,
	0x20, 0xa5, 0x94, 0xde, 0x0f, 0xc4, 0xd2, 0x60, 0x4d, 0xa6, 0xe3, 0xa9, 0x42, 0x61, 0x10, 0x1c,
	0x2c, 0x54, 0xcd, 0x34, 0x13, 0x29, 0xbe, 0x45, 0xfb, 0xc6, 0x25, 0x07, 0x91, 0xd2, 0xbb, 0x59,
	0x6b, 0x0d, 0xdf, 0xfe, 0xa0, 0xbe, 0xd3, 0x9b, 0x81, 0x8a, 0xa3, 0x24, 0x42, 0x73, 0xa7, 0x37,
	0xee, 0x33, 0x34, 0xb8, 0xdc, 0xae, 0x8e, 0x74, 0xbd, 0x8e, 0xa5, 0xd6, 0xd8, 0x81, 0xc6, 0x2a,
	0x7f, 0x8a, 0xe4, 0xa8, 0xa4, 0x63, 0x74, 0x8d, 0x5e, 0x05, 0x5b, 0x50, 0x2b, 0x5a, 0xa7, 0xd4,
	0x35, 0x7a, 0x75, 0x6c, 0x40, 0x79, 0xbf, 0xda, 0x49, 0xc7, 0x3c, 0x25, 0x15, 0xc5, 0x89, 0x53,
	0xee, 0x1a, 0x3d, 0xdb, 0x7d, 0x05, 0xa0, 0x87, 0xe4, 0x6d, 0xac, 0x37, 0x5c, 0x7e, 0xa4, 0xdb,
	0x41, 0xcb, 0x38, 0x03, 0xd5, 0xd1, 0x02, 0x53, 0x7d, 0xae, 0x0b, 0x88, 0x7b, 0xa6, 0xa6, 0x1c,
	0xeb, 0xb6, 0x3d, 0x48, 0xed, 0x7e, 0xf9, 0xb4, 0xa0, 0x16, 0xa9, 0x5c, 0x25, 0xa5, 0x57, 0xdc,
	0xeb, 0x33, 0x5d, 0x2b, 0x6c, 0x42, 0x35, 0x96, 0xfa, 0xb0, 0x4d, 0x0a, 0x51, 0x1b, 0x2a, 0x49,
	0xf4, 0x2e, 0xf7, 0xd9, 0x05, 0xbb, 0x3f, 0x02, 0xab, 0x00, 0x4d, 0x8f, 0x4a, 0x22, 0x42, 0x93,
	0x7a, 0x1e, 0x17, 0xd3, 0x25, 0x1b, 0x0a, 0x9f, 0xcd, 0xef, 0x88, 0x81, 0x1d, 0x20, 0xe7, 0xce,
	0x0b, 0xc7, 0xd4, 0x0f, 0x88, 0xf9, 0xe7, 0xe7, 0x3d, 0x29, 0xf7, 0x6f, 0xa0, 0x1a, 0xb2, 0x8c,
	0xd3, 0x06, 0x3b, 0x64, 0xf9, 0xc6, 0x78, 0xf8, 0xb2, 0x24, 0x06, 0xfe, 0x87, 0xd6, 0xa9, 0x7a,
	0x08, 0xf9, 0x82, 0x72, 0x8f, 0x94, 0xfa, 0x2c, 0x77, 0xe5, 0x99, 0x21, 0x5a, 0x50, 0xa3, 0xb3,
	0xe9, 0xa3, 0x08, 0x47, 0xe4, 0x1f, 0x5e, 0xc1, 0x45, 0x16, 0x66, 0x93, 0x21, 0x17, 0x6c, 0xe1,
	0x09, 0x3f, 0x98, 0xd3, 0x27, 0xdf, 0x23, 0x5f, 0x01, 0x5e, 0x42, 0x27, 0xdb, 0x8a, 0x4a, 0xa4,
	0x26, 0xc3, 0xc9, 0x84, 0x7c, 0x07, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x96, 0x1e, 0xc1,
	0xbf, 0x01, 0x00, 0x00,
}
